### ISSUE TITLE
why rebuild ?

### ISSUE THREAD

**Issue by zhaishengfu** [danilw/flat-maze#1]
hello, is the rebuild essential? I does not rebuild and run directly using 3.2 version, it is not correct but the collision seems right, and collision is the most important thing i am interested, so can i use the shader directly without rebuilding ?

**Comment by zhaishengfu** [comment]
I have retuild it, and the result is wonderful. Thanks for this amazing demo. And i looked some information. your changing code is use 32 float precision, right? in your code, you used 32 precision for viewport?? then what if the performance influence? the original is 16 float, you changed 32 to replace default viewport, will this cause big performance drawback?? if not, why officinal godot does not use 32 float??

**Comment by danilw** [comment]
Hello. I try answer questions.

I dont understand, does it work for you? No problem in launching? I test it my self on Godot 3.2.1 stable with rebuild to use 32bit float, and everything work.

**1.** why 32-yes I need 32 bit viewport to store all data for each particle, read this shader source there logic [particles_fbo_logic.shader](https://github.com/danilw/flat-maze/blob/master/flat_maze/shaders/scene2/particles_fbo_logic.shader)
```
// data
// in [x,y,z,w]
// x-posx
// y-posy
// z-0xffff-velx, 0xff-data
// w-0xffff-vely, 0xff-data
```
I need that much data and 16bit float is not enough for that

**2.** Reason why Godot use 16 bit Viewport(framebuffer) is because Mobile support, Mobile from 2010-2015 drop performance very hard like 3-5 times slower on 32bit then on 16 bit.

PC GPU, even integrated 2010+ year do not have any difference between performance on 16bit and 32bit framebuffer. Performance literally the same, all data in PC GPU exist as 32bit float, in all shaders, only on mobile this data is 8 or 16 bit for shader calculation, and using 32 bit there is huge slowdown, this why it so much slower on mobile GPU.

**Comment by zhaishengfu** [comment]
Ok thanks for your detailed reply. I rebuild as you said and it workd perfectly. I will look carefully the code and understand it better. Thanks again for the demo and reply
