### ISSUE TITLE
why 10 * 2 logic viewport??

### ISSUE THREAD

**Issue by zhaishengfu** [danilw/flat-maze#3]
Hello, I have some questions about your flat maze : )

1. you have 10 * 2 logic and logic_buf viewport, and i see you get position and other attributes by texelFetch. Why  you not pass uniform parameter as these values, for example , use one float position to store your texelFecth(0, 0 ) for the position? Is it for better performance?? 

2. you have told me that you compiled godot engine from 16 bit viewport to 32 bit viewport.  if you use 16 bit viewport, pixel.xyzw will be 16 bit seperately, right? that is , one pixel will use 16 * 4 bit to store its data

3. if above is correct, I can recode your logic with 16 bit viewport, just change the pixel texelFetch information to uniform parameter and set parameters by using gdscript, right?

**Comment by danilw** [comment]
best answer to test everything you want without deal with my "bad code in Godot project":
**get this shader https://www.shadertoy.com/view/tstSz7 and *understand it* and make it work in your Godot**

1. *logic* viewport in scene2.tscn file for "player movement logic" 
look *player* sprite node on same scene, *logic* linked to this sprite

logic of *logic* viewport is:
it read *particle buffer* and check if the current position of `player` hit any of particles and do "slowdown" if player hit any of particles (also decrease player HP when player hit particle with type enemy(not trees))

I do not know why its size 10x2 when I use just two pixels `(0,0)` and `(1,0)`
```
void mainImage( out vec4 fragColor, in vec2 fragCoord ,in vec2 iResolution)
{
	fragColor=vec4(0.);
	ivec2 ipx=ivec2(fragCoord);
	if(ipx==ivec2(0,0)){
		fragColor=screen_pos();
	}
	if(ipx==ivec2(1,0)){
		fragColor=player_collision();
	}
	
}
```
**maybe I just forgot to change its size to 1x2,I dont remember**

> and i see you get position and other attributes by texelFetch. Why you not pass uniform parameter as these values, for example , use one float position to store your texelFecth(0, 0 ) for the position? Is it for better performance??

I do not like "separating of logic code" and frame sinchronization CPU-GPU, like having "player logic" on CPU(gdscript) just few functions and then collision check on GPU because passing "GPU data to RAM" impossible slow, so collision check have to be on GPU when "some of player control can be moved to GDScript"... it not worth its effort for me, you do as you wish

2. 
> you have told me that you compiled godot engine from 16 bit viewport to 32 bit viewport. if you use 16 bit viewport, pixel.xyzw will be 16 bit seperately, right? that is , one pixel will use 16 * 4 bit to store its data

default (unmodified) Godot viewport is 16-bit

I want point that **I use 32 bit as int `0xffffff` not as uint `0xffffffff` (that my mistake)

so I have `0xff` unused

3.
>if above is correct, I can recode your logic with 16 bit viewport, just change the pixel texelFetch information to uniform parameter and set parameters by using gdscript, right?

to proper use 32bit you have to change functions to encode/decode data (search encode and decde in shaders)
replace it to this
```
// input is 0xf1f2f3f4 output is [0xf1][0xf2][0xf3][0xf4]
uvec4 decodeval32(uint varz) {
    uvec4 iret=uvec4(0);
    iret.x=varz>>24;
    iret.y=(varz>>16)&0xffu;
    iret.z=(varz>>8)&0xffu;
    iret.w=(varz>>0)&0xffu;
    return iret;
}

// input is [0xf1][0xf2][0xf3][0xf4] output is 0xf1f2f3f4
uint encodeval32(uvec4 colz) {
    return uint((colz[0]<<24)&0xff000000u|(colz[1]<< 16)&0x00ff0000u|(colz[2]<< 8)&0x0000ff00u|(colz[3]<< 0)&0x000000ffu);
}

// input is float from texelFetch(<FBO>,ipos,0).x/y/z/w
uint load_data(float val){
    return floatBitsToUint(val);
}

// input is [0xf1][0xf2][0xf3][0xf4] four times, output is vec4 to save as FBO color
vec4 pack_udata(uvec4 data1,uvec4 data2,uvec4 data3,uvec4 data4){
    return uintBitsToFloat(uvec4(encodeval32(data1), 
                 encodeval32(data2), 
                 encodeval32(data3), 
                 encodeval32(data4)));
}
```
and use `load_data` and `pack_udata` to save save load values, that make those unused `0xff` aviable

**Comment by danilw** [comment]
I think il update this my project to be less confused, il update it today like in few hours check it

**Comment by danilw** [comment]
about 16 bits:

16 bits is uint `0xffff` [8 bits][8 bits]
when minimum I need uint `0xffffff` [8][8][8] that 24 bits
so my logic can not use 16 bits(it can if you change it as I write below)

as you see my description on shaders:
```
// data
// in [x,y,z,w]
// x-posx
// y-posy
// z-0xffff-velx, 0xff-data
// w-0xffff-vely, 0xff-data
```

using 16 bits you have to cut velx/velt values to 8 bit `0xff` that `1/127=0.00787` (1/127 because speed can be posiitve and negative) float step for speed
it may be enough

**so to change this my game to 16 bit is only rework `particles_fbo_logic.shader`** (and other shaders that use its data) to decreasing velx/vely data

**Comment by zhaishengfu** [comment]
thanks for your reply, know better about your ideas.

**Comment by danilw** [comment]
I hope this info useful for you, feel free to ask anything you need

**Comment by zhaishengfu** [comment]
Another question, about your textureGrad function.

As i know, you use textureGrad for mipmap purpose, right? that is , for different zoom, it will have right resolution .

And i find that when setting different stretch mode, it will have different visual effect. 
your current setting is "2D", if i set this to "Viewport", when zoom and move there will be jitter . I find some information and I think this is related to your image. If I use low-resolution pixel sprite i should use "Viewport", otherwise I should use "2D", right?

**Comment by danilw** [comment]
zhaishengfu I updated my posts fixing few mistakes

> As i know, you use textureGrad for mipmap purpose, right? that is , for different zoom, it will have right resolution .

as I remember I use `textureGrad` because default (in texture function) mipmaps calculation become broken on high zoom, also default mipmaps broken in WebGL under ANGLE(that OpenGL to DX11 translator)
just change it to `texture` and look if it works for you

> And i find that when setting different stretch mode, it will have different visual effect.
your current setting is "2D", if i set this to "Viewport", when zoom and move there will be jitter . I find some information and I think this is related to your image. If I use low-resolution pixel sprite i should use "Viewport", otherwise I should use "2D", right?

I do not like Godot Viewport logic at all, and it bugged, just another bug I found last week https://github.com/godotengine/godot/issues/45428

there are problems in Godot viewport logic, and that *weird stuff* I do in scripts like having extra `fbo_self.gd` script to bind viewport to another buffer that declared before this buffer... and other code... just to dodge Godot bugs/features

about you question:
I think Godot wiki explain it https://docs.godotengine.org/en/stable/tutorials/viewports/multiple_resolutions.html?highlight=stretch%20mode#stretch-mode
![1](https://user-images.githubusercontent.com/24825887/106014189-4ad5ff00-60ce-11eb-9448-6cdf7166ef3a.png)
I use 2D because some reason... I dont remember, or maybe I just dont change it to needed... 

I mean use any Viewport logic that work for you (there no correct answer)

**Comment by zhaishengfu** [comment]
`there are problems in Godot viewport logic, and that weird stuff I do in scripts like having extra fbo_self.gd script to bind viewport to another buffer that declared before this buffer... and other code... just to dodge Godot bugs/features`

Oh I wonder why you use so many viewports... you mentioned `there are problems in Godot viewport logic`, is it serious mistake？ Indeed I want to realize this algorithm with your maze shader
https://www.youtube.com/watch?v=ZZY9YE7rZJw

If you have time you can see it， interesting ideas. Roughly say, It store its star postion in random function and render viewport based on position. I want to combine this with your maze shader to replace your "ground1", "ground2" with different planet texture, and with really big universe and different zoom, I think this will be cool.

**Comment by danilw** [comment]
> If you have time you can see it， interesting ideas. Roughly say, It store its star postion in random function and render viewport based on position. I want to combine this with your maze shader to replace your "ground1", "ground2" with different planet texture, and with really big universe and different zoom, I think this will be cool.

I have my projects to make and my ideas, even if it sound selfish, I do not want to work for "free" on some other ideas

all projects that come from my https://github.com/danilw/godot-utils-and-other (flat-maze one of it) it just "my test projects that I share" you can do with its logic almost anything you want, **code in those projects are bad**

> If you have time you can see it， interesting ideas

I watch video, for me its just "some another guy idea that I do not care" so ye...

my poiny - do it if you like, I not gonna spend my time to make code for you thats all. Only I can is answer your question and give simple tips that may be useful for you thats all.

> I want to combine this with your maze shader to replace your "ground1", "ground2" with different planet texture, and with really big universe and different zoom, I think this will be cool.

I can warn you that you say sound very complex, for me it may take maybe even year to develop is as I understand you want... so maybe it not worth your time, but do as you wish

**Comment by zhaishengfu** [comment]
I won't let you make code for me, Your reply helped me a alot :) . I will show you my final result when I finish.
Thanks again for your patient reply, good luck!

**Comment by danilw** [comment]
good luck to you too, and you dont owe me anything 
(you do not have to make something to show me I mean)

if you have not more questions for now, you can close this issue 
and open new latter if you need
